language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="batsat:."
  - DISTRO="ubuntu"
  - PRE_INSTALL_HOOK="sudo apt-get update && sudo apt-get install cargo -y && rustc --version"
  matrix:
  - PACKAGE="batsat" OCAML_VERSION="4.03"
  - PACKAGE="batsat" OCAML_VERSION="4.04"
  - PACKAGE="batsat" OCAML_VERSION="4.05"
  - PACKAGE="batsat" OCAML_VERSION="4.06"
  - PACKAGE="batsat" OCAML_VERSION="4.07"
